use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', generate_multiple_pod_projects: true

post_install do |installer|
  installer.generated_projects.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'SIContactManager_Example' do
  pod 'SIContactManager', :path => '../'

  target 'SIContactManager_Tests' do
    inherit! :search_paths

    
  end
end
